linux-dpdk: do not warn on deprecated register
rte_byteorder.h:53:2: error: 'register' storage
class specifier is deprecated and incompatible with C++1z
      [-Werror,-Wdeprecated-register]
        register uint16_t x = _x;

Signed-off-by: Maxim Uvarov <maxim.uvarov@linaro.org>